const { SITE_ORIGIN, buildPublicIndex } = require('./_posts');

// Posts with `external: true` (pages not generated by the CMS, e.g. the original
// hand-built article) provide their own <url> entry via the posts index below,
// so they must not also be listed here or the sitemap will contain a duplicate.
const STATIC_URLS = [
  { loc: '/', changefreq: 'weekly', priority: '1.0' },
  { loc: '/best-seo-expert-in-nepal/', changefreq: 'weekly', priority: '0.9' },
  { loc: '/blog/', changefreq: 'weekly', priority: '0.8' },
];

function escapeXml(s) {
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

function todayIso() {
  return new Date().toISOString().slice(0, 10);
}

function buildSitemap(posts, pages) {
  const published = buildPublicIndex(posts);
  const publishedPages = (pages || []).filter((p) => p.status === 'published');
  const today = todayIso();
  const staticEntries = STATIC_URLS.map(
    (u) =>
      `  <url>\n    <loc>${SITE_ORIGIN}${u.loc}</loc>\n    <lastmod>${today}</lastmod>\n    <changefreq>${u.changefreq}</changefreq>\n    <priority>${u.priority}</priority>\n  </url>`
  );
  const postEntries = published.map(
    (p) =>
      `  <url>\n    <loc>${SITE_ORIGIN}${p.url}</loc>\n    <lastmod>${(p.publishDate || today).slice(0, 10)}</lastmod>\n    <changefreq>monthly</changefreq>\n    <priority>0.6</priority>\n  </url>`
  );
  const pageEntries = publishedPages.map(
    (p) =>
      `  <url>\n    <loc>${SITE_ORIGIN}/${p.slug}/</loc>\n    <lastmod>${(p.updatedAt || today).slice(0, 10)}</lastmod>\n    <changefreq>monthly</changefreq>\n    <priority>0.7</priority>\n  </url>`
  );
  return (
    '<?xml version="1.0" encoding="UTF-8"?>\n' +
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n' +
    staticEntries.concat(pageEntries).concat(postEntries).join('\n') +
    '\n</urlset>\n'
  );
}

function buildRss(posts) {
  const published = buildPublicIndex(posts);
  const items = published
    .map(
      (p) =>
        `    <item>\n` +
        `      <title>${escapeXml(p.title)}</title>\n` +
        `      <link>${SITE_ORIGIN}${p.url}</link>\n` +
        `      <guid>${SITE_ORIGIN}${p.url}</guid>\n` +
        `      <pubDate>${new Date(p.publishDate || Date.now()).toUTCString()}</pubDate>\n` +
        `      <description>${escapeXml(p.excerpt || '')}</description>\n` +
        `    </item>`
    )
    .join('\n');
  return (
    '<?xml version="1.0" encoding="UTF-8"?>\n' +
    '<rss version="2.0">\n' +
    '<channel>\n' +
    '  <title>Prabal Raj Shakya — Blog</title>\n' +
    `  <link>${SITE_ORIGIN}/blog/</link>\n` +
    '  <description>SEO and digital marketing insights for Nepali businesses.</description>\n' +
    '  <language>en</language>\n' +
    `  <lastBuildDate>${new Date().toUTCString()}</lastBuildDate>\n` +
    items +
    '\n</channel>\n' +
    '</rss>\n'
  );
}

module.exports = { buildSitemap, buildRss };
